macro(GeneratePythonProto)
	set(PROTOFILES_DIR PROTOFILES_DIR-NOTFOUND CACHE PATH "Protobuf files")
	if(NOT PROTOFILES_DIR)
	  message(FATAL_ERROR "Protobuf files wasn't provided. Use -DPROTOFILES_DIR configuration option.")  
	endif()
  file(GLOB_RECURSE PROTO_FILES ${PROTOFILES_DIR}/*.proto)
  protobuf_generate_python(PROTO_PY ${PROTO_FILES})
  add_custom_target(PythonProto DEPENDS ${PROTO_PY})
endmacro(GeneratePythonProto)
